In [7]:
import pandas as pd

In [8]:
df = pd.read_csv('deforestation.csv')

In [9]:
df

,Tile ID,Image ID,Date,Region,Country,Biome Type,Latitude,Longitude,Elevation (m),Slope (°),...,Distance to River (km),"Protected Area (1=Yes,0=No)","Logging Concession (1=Yes,0=No)",Population Density (per km²),Forest Loss Last 3Y (%),Cumulative Deforested Area (%),"Deforestation Event (Yes=1,No=0)",Predicted Risk Score,Dataset Split,Image File Path
0,T0001,T0001_20240101,1/1/2024,Congo Basin,DRC,Tropical Rainforest,-3.07997,17.87613,488.1,2.8,...,6.10,0,0,13.7,33.1,0.00,0,0.897,test,s3://sat-imagery/congobasin/T0001/2024/01/01/t...
1,T0001,T0001_20240201,2/1/2024,Congo Basin,DRC,Tropical Rainforest,-3.07997,17.87613,488.1,2.8,...,6.10,0,0,13.7,33.1,0.00,0,0.898,test,s3://sat-imagery/congobasin/T0001/2024/02/01/t...
2,T0001,T0001_20240301,3/1/2024,Congo Basin,DRC,Tropical Rainforest,-3.07997,17.87613,488.1,2.8,...,6.10,0,0,13.7,33.1,0.00,0,0.900,test,s3://sat-imagery/congobasin/T0001/2024/03/01/t...
3,T0001,T0001_20240401,4/1/2024,Congo Basin,DRC,Tropical Rainforest,-3.07997,17.87613,488.1,2.8,...,6.10,0,0,13.7,33.1,0.00,0,0.887,test,s3://sat-imagery/congobasin/T0001/2024/04/01/t...
4,T0001,T0001_20240501,5/1/2024,Congo Basin,DRC,Tropical Rainforest,-3.07997,17.87613,488.1,2.8,...,6.10,0,0,13.7,33.1,0.00,0,0.883,test,s3://sat-imagery/congobasin/T0001/2024/05/01/t...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1095,T0110,T0110_20240601,6/1/2024,SE Asia,Papua New Guinea,Tropical Rainforest,0.10310,116.53879,0.0,5.0,...,3.11,0,0,6.7,15.6,1.96,1,0.906,train,s3://sat-imagery/seasia/T0110/2024/06/01/tile.tif
1096,T0110,T0110_20240701,7/1/2024,SE Asia,Papua New Guinea,Tropical Rainforest,0.10310,116.53879,0.0,5.0,...,3.11,0,0,6.7,15.6,1.96,1,0.879,train,s3://sat-imagery/seasia/T0110/2024/07/01/tile.tif
1097,T0110,T0110_20240801,8/1/2024,SE Asia,Papua New Guinea,Tropical Rainforest,0.10310,116.53879,0.0,5.0,...,3.11,0,0,6.7,15.6,1.96,1,0.913,train,s3://sat-imagery/seasia/T0110/2024/08/01/tile.tif
1098,T0110,T0110_20240901,9/1/2024,SE Asia,Papua New Guinea,Tropical Rainforest,0.10310,116.53879,0.0,5.0,...,3.11,0,0,6.7,15.6,2.73,1,0.918,train,s3://sat-imagery/seasia/T0110/2024/09/01/tile.tif
1099,T0110,T0110_20241001,10/1/2024,SE Asia,Papua New Guinea,Tropical Rainforest,0.10310,116.53879,0.0,5.0,...,3.11,0,0,6.7,15.6,2.73,1,0.898,train,s3://sat-imagery/seasia/T0110/2024/10/01/tile.tif

In [11]:
def clean_col_names(df):
    cols = df.columns
    new_cols = []
    for col in cols:
        new_col = col.replace(' ', '_').replace('(%)','percent').replace('(°)', 'deg').replace('(°C)','celcius').replace('(m)','m').replace('(7d)','7d').replace('(1=Yes,0=No)','bool').replace('(per_km²)','per_km2').lower()
        new_cols.append(new_col)
    df.columns = new_cols
    return df
df = clean_col_names(df)
print(df.columns)

Index(['tile_id', 'image_id', 'date', 'region', 'country', 'biome_type',
       'latitude', 'longitude', 'elevation_m', 'slope_deg', 'rainfall_(mm)',
       'temperature_celcius', 'cloud_cover_percent', 'fire_alerts_7d',
       'ndvi_(vegetation_index)', 'ndmi_(moisture_index)',
       'evi_(enhanced_vegetation_index)', 'tree_cover_percent',
       'canopy_height_m', 'distance_to_road_(km)',
       'distance_to_settlement_(km)', 'distance_to_river_(km)',
       'protected_area_bool', 'logging_concession_bool',
       'population_density_per_km2', 'forest_loss_last_3y_percent',
       'cumulative_deforested_area_percent',
       'deforestation_event_(yes=1,no=0)', 'predicted_risk_score',
       'dataset_split', 'image_file_path'],
      dtype='object')

In [13]:
df['date'] = pd.to_datetime(df['date'])
print(df['date'])

0      2024-01-01
1      2024-02-01
2      2024-03-01
3      2024-04-01
4      2024-05-01
          ...
1095   2024-06-01
1096   2024-07-01
1097   2024-08-01
1098   2024-09-01
1099   2024-10-01
Name: date, Length: 1100, dtype: datetime64[ns]

In [14]:
categorical_cols = ['region','country','biome_type','dataset_split']
for col in categorical_cols:
    print(df[col].unique())

['Congo Basin' 'SE Asia' 'Amazon']
['DRC' 'Papua New Guinea' 'Colombia' 'Congo' 'Indonesia' 'Peru' 'Malaysia'
 'Brazil' 'Gabon']
['Tropical Rainforest']
['test' 'train' 'val']

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1100 entries, 0 to 1099
Data columns (total 31 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   tile_id                             1100 non-null   object
 1   image_id                            1100 non-null   object
 2   date                                1100 non-null   datetime64[ns]
 3   region                              1100 non-null   object
 4   country                             1100 non-null   object
 5   biome_type                          1100 non-null   object
 6   latitude                            1100 non-null   float64
 7   longitude                           1100 non-null   float64
 8   elevation_m                         1100 non-null   float64
 9   slope_deg                           1100 non-null   float64
 10  rainfall_(mm)                       1100 non-null   float64
 11  temperature_celcius                 1100 non-null   float64
 12  cloud_cover_percent                 1100 non-null   float64
 13  fire_alerts_7d                      1100 non-null   int64
 14  ndvi_(vegetation_index)             1100 non-null   float64
 15  ndmi_(moisture_index)               1100 non-null   float64
 16  evi_(enhanced_vegetation_index)     1100 non-null   float64
 17  tree_cover_percent                  1100 non-null   float64
 18  canopy_height_m                     1100 non-null   float64
 19  distance_to_road_(km)               1100 non-null   float64
 20  distance_to_settlement_(km)         1100 non-null   float64
 21  distance_to_river_(km)              1100 non-null   float64
 22  protected_area_bool                 1100 non-null   int64
 23  logging_concession_bool             1100 non-null   int64
 24  population_density_per_km2          1100 non-null   float64
 25  forest_loss_last_3y_percent         1100 non-null   float64
 26  cumulative_deforested_area_percent  1100 non-null   float64
 27  deforestation_event_(yes=1,no=0)    1100 non-null   int64
 28  predicted_risk_score                1100 non-null   float64
 29  dataset_split                       1100 non-null   object
 30  image_file_path                     1100 non-null   object
dtypes: datetime64[ns](1), float64(19), int64(4), object(7)
memory usage: 266.5+ KB

In [16]:
print(df.head())

  tile_id        image_id       date       region country  \
0   T0001  T0001_20240101 2024-01-01  Congo Basin     DRC
1   T0001  T0001_20240201 2024-02-01  Congo Basin     DRC
2   T0001  T0001_20240301 2024-03-01  Congo Basin     DRC
3   T0001  T0001_20240401 2024-04-01  Congo Basin     DRC
4   T0001  T0001_20240501 2024-05-01  Congo Basin     DRC

            biome_type  latitude  longitude  elevation_m  slope_deg  ...  \
0  Tropical Rainforest  -3.07997   17.87613        488.1        2.8  ...
1  Tropical Rainforest  -3.07997   17.87613        488.1        2.8  ...
2  Tropical Rainforest  -3.07997   17.87613        488.1        2.8  ...
3  Tropical Rainforest  -3.07997   17.87613        488.1        2.8  ...
4  Tropical Rainforest  -3.07997   17.87613        488.1        2.8  ...

   distance_to_river_(km)  protected_area_bool  logging_concession_bool  \
0                     6.1                    0                        0
1                     6.1                    0                        0
2                     6.1                    0                        0
3                     6.1                    0                        0
4                     6.1                    0                        0

   population_density_per_km2  forest_loss_last_3y_percent  \
0                        13.7                         33.1
1                        13.7                         33.1
2                        13.7                         33.1
3                        13.7                         33.1
4                        13.7                         33.1

   cumulative_deforested_area_percent  deforestation_event_(yes=1,no=0)  \
0                                 0.0                                 0
1                                 0.0                                 0
2                                 0.0                                 0
3                                 0.0                                 0
4                                 0.0                                 0

   predicted_risk_score  dataset_split  \
0                 0.897           test
1                 0.898           test
2                 0.900           test
3                 0.887           test
4                 0.883           test

                                     image_file_path
0  s3://sat-imagery/congobasin/T0001/2024/01/01/t...
1  s3://sat-imagery/congobasin/T0001/2024/02/01/t...
2  s3://sat-imagery/congobasin/T0001/2024/03/01/t...
3  s3://sat-imagery/congobasin/T0001/2024/04/01/t...
4  s3://sat-imagery/congobasin/T0001/2024/05/01/t...

[5 rows x 31 columns]

In [17]:
print(df.isnull().sum())

tile_id                               0
image_id                              0
date                                  0
region                                0
country                               0
biome_type                            0
latitude                              0
longitude                             0
elevation_m                           0
slope_deg                             0
rainfall_(mm)                         0
temperature_celcius                   0
cloud_cover_percent                   0
fire_alerts_7d                        0
ndvi_(vegetation_index)               0
ndmi_(moisture_index)                 0
evi_(enhanced_vegetation_index)       0
tree_cover_percent                    0
canopy_height_m                       0
distance_to_road_(km)                 0
distance_to_settlement_(km)           0
distance_to_river_(km)                0
protected_area_bool                   0
logging_concession_bool               0
population_density_per_km2            0
forest_loss_last_3y_percent           0
cumulative_deforested_area_percent    0
deforestation_event_(yes=1,no=0)      0
predicted_risk_score                  0
dataset_split                         0
image_file_path                       0
dtype: int64